FROM redis:6.2-alpine

RUN mkdir -p /var/lib/redis/
RUN mkdir -p /etc/systemd/system/
RUN mkdir -p /etc/redis/

# copying our custom configuration
COPY ./docker/redis/redis.service /etc/systemd/system/redis.service
COPY ./docker/redis/redis.conf /etc/redis/redis.conf


RUN chmod 777 /etc
RUN chown -R redis:redis /var/lib/redis/.
RUN chown -R redis:redis /var/
RUN chown -R redis:redis /etc/
