# Generated by Django 3.0.8 on 2022-01-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_auto_20220109_1755"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="UserPhotos",
        ),
    ]
