# Generated by Django 3.0.8 on 2022-01-14 11:12

from django.db import migrations, models

import base.file_dir


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_auto_20220112_1756"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userphotos",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=base.file_dir.profile_upload_path
            ),
        ),
    ]
