# Generated by Django 3.0.8 on 2022-01-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_auto_20220114_1112"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="house_number_and_building_name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="land_mark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="street_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
