# Generated by Django 3.0.8 on 2022-02-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_user_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_profile_completely_filled",
            field=models.BooleanField(default=False),
        ),
    ]
