# Generated by Django 3.0.8 on 2022-02-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_user_is_profile_completely_filled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="father_name",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="father name"
            ),
        ),
    ]
