# Generated by Django 3.0.8 on 2022-02-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_user_father_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userphotos",
            unique_together=set(),
        ),
    ]
