# Generated by Django 3.0.8 on 2022-02-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_auto_20220206_1718"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usermobilenumber",
            unique_together={("user", "mobile_number")},
        ),
    ]
