# Generated by Django 3.0.8 on 2022-02-13 05:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_auto_20220212_1341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="geo_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, null=True, srid=4326
            ),
        ),
    ]
