# Generated by Django 3.0.8 on 2022-02-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_user_referral_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="visitor",
            unique_together=set(),
        ),
    ]
