# Generated by Django 3.1.14 on 2022-03-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_user_is_online"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="is_shipping",
        ),
    ]
