# Generated by Django 3.1.14 on 2022-04-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_address_is_shipping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userphotos',
            options={'ordering': ['-id']},
        ),
    ]
