default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
  - repo: local
    hooks:
    - id: migrations-check
      language: system
      name: Check for uncreated migrations.
      entry: bash -c "./manage.py makemigrations --check --dry-run"
      types: ["python"]
      pass_filenames: false
