version: '3'

services:
  redisapp:
    restart: always
    image: redis:5.0.4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
     - app-network
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"

  django:
    build:
      context: .
      dockerfile: ./docker/django/dockerfile
    restart: always
    command: /gunicorn.sh
    volumes:
      - /mnt/media/external:/app/media
    networks:
     - app-network
    expose:
      - "80"
    links:
      - celeryapp
      - redisapp
    env_file:
      - .env

  nginx:
    image: nginx:1.13-alpine
    restart: always
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/dockerfile
    volumes:
      - /mnt/media/external:/app/media
    ports:
      - "80:80"
    links:
      - django
      - redisapp
    networks:
     - app-network

  celeryapp:
    build:
      context: .
      dockerfile: ./docker/celery/dockerfile
    restart: always
    command: /celery.sh
    networks:
      - app-network
    environment:
        - C_FORCE_ROOT=1
    env_file:
      - ./.env
    links:
      - redisapp
    depends_on:
      - redisapp

networks:
  app-network:
    driver: bridge
