# Generated by Django 3.0.8 on 2022-02-14 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralAndEarn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                ("referral_code", models.CharField(blank=True, max_length=255)),
                ("earn_amount", models.FloatField(default=0.0)),
                (
                    "transaction_reference",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "earn_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earn_customer_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refer_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refer_customer_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("refer_customer", "earn_customer"),
                    ("referral_code", "earn_customer"),
                },
            },
        ),
    ]
