# Generated by Django 3.0.8 on 2022-02-16 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("promotion", "0002_referralandearn"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralandearn",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="referralandearn",
            unique_together={
                ("referral_code", "customer"),
                ("refer_customer", "customer"),
            },
        ),
        migrations.RemoveField(
            model_name="referralandearn",
            name="earn_customer",
        ),
    ]
