# Generated by Django 3.0.8 on 2022-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0003_auto_20220216_1623"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountvoucher",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
