# Generated by Django 3.0.8 on 2022-02-18 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_transaction_payment_response"),
        ("promotion", "0006_auto_20220217_1857"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralandearn",
            name="transaction_reference",
        ),
        migrations.AddField(
            model_name="referralandearn",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_transaction",
                to="wallet.Transaction",
            ),
        ),
    ]
