# Generated by Django 3.0.8 on 2022-02-18 22:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("promotion", "0007_auto_20220218_2229"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="referralandearn",
            unique_together={
                ("refer_customer", "customer"),
                ("customer",),
                ("referral_code", "customer"),
            },
        ),
    ]
