# Generated by Django 3.0.8 on 2022-02-21 18:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0008_auto_20220218_2238"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountvoucher",
            name="terms_and_conditions",
            field=ckeditor.fields.RichTextField(default=""),
        ),
    ]
