# Generated by Django 3.0.8 on 2022-02-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0009_discountvoucher_terms_and_conditions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discountvoucher",
            name="collections",
        ),
    ]
