# Generated by Django 3.1.14 on 2022-04-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0010_remove_discountvoucher_collections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountvoucher',
            options={'ordering': ['-id']},
        ),
    ]
