# Generated by Django 3.0.8 on 2022-01-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productcollection",
            old_name="background",
            new_name="background_color",
        ),
        migrations.RenameField(
            model_name="productcollection",
            old_name="bottem_line",
            new_name="bottem_line_color",
        ),
    ]
