# Generated by Django 3.0.8 on 2022-01-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0002_auto_20220122_1124"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupstructure",
            name="is_main",
            field=models.BooleanField(default=True),
        ),
    ]
