# Generated by Django 3.0.8 on 2022-01-22 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0003_groupstructure_is_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupstructure",
            name="bottem_line_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_bottem_line_color",
                to="group.Color",
            ),
        ),
        migrations.AlterField(
            model_name="groupstructure",
            name="background_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_background_color",
                to="group.Color",
            ),
        ),
    ]
