# Generated by Django 3.0.8 on 2022-01-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_auto_20220116_1913"),
        ("group", "0004_auto_20220122_1652"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcollection",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_product_collection",
                to="store.Store",
            ),
        ),
    ]
