# Generated by Django 3.0.8 on 2022-01-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0006_auto_20220123_0850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="alignment",
            field=models.CharField(
                blank=True,
                choices=[("1", "Horizontal"), ("2", "Vertical")],
                default="1",
                max_length=5,
                null=True,
            ),
        ),
    ]
