# Generated by Django 3.0.8 on 2022-01-29 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0007_auto_20220123_0927"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_collection",
                to="group.GroupStructure",
            ),
        ),
    ]
