# Generated by Django 3.0.8 on 2022-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0008_auto_20220129_1857"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="sequence",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="groupstructure",
            name="sequence",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productcollection",
            name="sequence",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
