# Generated by Django 3.0.8 on 2022-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0009_auto_20220130_0903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="alignment",
            field=models.CharField(
                blank=True,
                choices=[("horizontal", "Horizontal"), ("vertical", "Vertical")],
                default="horizontal",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="groupstructure",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("level 1", "Level 1"),
                    ("level 2", "Level 2"),
                    ("level 3", "Level 3"),
                ],
                default="level 1",
                max_length=10,
                null=True,
            ),
        ),
    ]
