# Generated by Django 3.0.8 on 2022-02-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_auto_20220130_0908"),
        ("group", "0010_auto_20220130_0925"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupstructure",
            name="store",
        ),
        migrations.AddField(
            model_name="groupstructure",
            name="store",
            field=models.ManyToManyField(
                blank=True, related_name="store_group", to="store.Store"
            ),
        ),
    ]
