# Generated by Django 3.0.8 on 2022-02-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0011_auto_20220211_0418"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptype",
            name="display",
            field=models.CharField(default="", max_length=255),
        ),
    ]
