# Generated by Django 3.0.8 on 2022-01-11 20:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryBoy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "current_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("is_approve", models.BooleanField(default=False)),
                (
                    "payout_balance",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offline", "Offline"),
                            ("online", "Online"),
                            ("delivery_on_the_way", "Delivery on the way"),
                            ("store_attend", "Store attend"),
                            ("customer_attend", "Attand to customer"),
                            ("back_to_store", "Back to store"),
                        ],
                        default="offline",
                        max_length=255,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_boy_store",
                        to="store.Store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_boy_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryBoyVehicleInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("auto_rickshaw", "Auto-rickshaw"),
                            ("cycle", "Cycle"),
                            ("motor_cycle", "Motor cycle"),
                            ("mini_truck", "Mini truck"),
                            ("other", "Other"),
                            ("truck", "Truck"),
                        ],
                        default="motor_cycle",
                        max_length=255,
                    ),
                ),
                (
                    "vehicle_license_number",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "delivery_boy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_information",
                        to="delivery.DeliveryBoy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryBoyPayoutInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "bank_account_ifsc",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "bank_account_number",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "bank_account_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "bank_branch_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "bank_account_proof",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "bank_branch_address",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "delivery_boy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_boy_payout_account",
                        to="delivery.DeliveryBoy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryBoyIDProof",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id_number",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "id_proof_type",
                    models.CharField(
                        choices=[
                            ("aadhar_card", "Aadhar card"),
                            ("address_proof", "Address proof"),
                            ("driving_license", "Driving license"),
                            ("other", "Other"),
                            ("pan_card", "Pan card"),
                            ("voter_id", "Voter ID"),
                        ],
                        default="aadhar_card",
                        max_length=255,
                    ),
                ),
                ("soft_copy", models.ImageField(blank=True, null=True, upload_to="")),
                ("is_verify", models.BooleanField(default=False)),
                (
                    "delivery_boy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_boy_vehicle_information",
                        to="delivery.DeliveryBoy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
