# Generated by Django 3.0.8 on 2022-01-12 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryBoyReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("text", models.TextField(default="")),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("1", "Very bad"),
                            ("2", "Bad"),
                            ("3", "Okay"),
                            ("4", "Good"),
                            ("5", "Excellent"),
                        ],
                        default="3",
                        max_length=255,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_review_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_boy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_boy_review",
                        to="delivery.DeliveryBoy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
