# Generated by Django 3.0.8 on 2022-01-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_deliveryboyreview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryboypayoutinformation",
            old_name="bank_account_ifsc",
            new_name="bank_account_ifsc_code",
        ),
    ]
