# Generated by Django 3.0.8 on 2022-01-14 11:12

from django.db import migrations, models

import base.file_dir


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_auto_20220112_1836"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryboyidproof",
            name="soft_copy",
            field=models.ImageField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryboypayoutinformation",
            name="bank_account_proof",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.file_dir.delivery_boy_bank_account_proof_upload_path,
            ),
        ),
    ]
