# Generated by Django 3.0.8 on 2022-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_auto_20220114_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryboy",
            name="status",
            field=models.CharField(
                choices=[
                    ("offline", "Offline"),
                    ("online", "Online"),
                    ("delivery_on_the_way", "Delivery on the way"),
                    ("order_picked_up", "Order picked up"),
                    ("store_attend", "Store attend"),
                    ("customer_attend", "Attand to customer"),
                    ("back_to_store", "Back to store"),
                ],
                default="offline",
                max_length=255,
            ),
        ),
    ]
