# Generated by Django 3.0.8 on 2022-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0006_auto_20220115_1212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryboydocument",
            name="id_proof_type",
            field=models.CharField(
                choices=[
                    ("aadhar_card", "Aadhar card"),
                    ("address_proof", "Address proof"),
                    ("bank_account_passbook", "Bank account passbook"),
                    ("driving_license", "Driving license"),
                    ("other", "Other"),
                    ("pan_card", "Pan card"),
                    ("voter_id", "Voter ID"),
                ],
                default="aadhar_card",
                max_length=255,
            ),
        ),
    ]
