# Generated by Django 3.0.8 on 2022-01-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0008_auto_20220115_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryboyreview",
            name="rating",
            field=models.CharField(
                choices=[
                    ("1", "Very bad"),
                    ("2", "Bad"),
                    ("3", "Okay"),
                    ("4", "Good"),
                    ("5", "Excellent"),
                ],
                default="3",
                max_length=5,
            ),
        ),
    ]
