# Generated by Django 3.0.8 on 2022-01-26 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0009_auto_20220123_0928"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCharges",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                ("amount", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "delivery_charge",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
