# Generated by Django 3.0.8 on 2022-02-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0010_deliverycharges"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverycharges",
            name="amount",
        ),
        migrations.AddField(
            model_name="deliverycharges",
            name="amount_ending_range",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="deliverycharges",
            name="amount_starting_range",
            field=models.FloatField(default=0.0),
        ),
    ]
