# Generated by Django 3.0.8 on 2022-02-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0011_auto_20220205_1017"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryboydocument",
            name="is_verify",
        ),
        migrations.AddField(
            model_name="deliveryboydocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
