# Generated by Django 3.0.8 on 2022-02-05 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0013_deliveryboyvehicleinformation_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryBoyVehiclePhotos",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "original",
                    models.ImageField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                    ),
                ),
                ("alt_text", models.TextField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="deliveryboyvehicleinformation",
            name="photos",
            field=models.ManyToManyField(
                blank=True,
                related_name="delivery_boy_vehicle_photos",
                to="delivery.DeliveryBoyVehiclePhotos",
            ),
        ),
    ]
