# Generated by Django 3.0.8 on 2022-02-05 21:48

from django.db import migrations, models
import django.utils.timezone
import base.file_dir


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0014_auto_20220205_2139"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryBoyDocumentPhotos",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "original",
                    models.ImageField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                    ),
                ),
                ("alt_text", models.TextField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="deliveryboydocument",
            name="soft_copy",
        ),
        migrations.AlterField(
            model_name="deliveryboyvehiclephotos",
            name="original",
            field=models.ImageField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryboyvehiclephotos",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryboyvehiclephotos",
            name="webp_image",
            field=models.ImageField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deliveryboydocument",
            name="photos",
            field=models.ManyToManyField(
                blank=True,
                related_name="delivery_boy_document_photos",
                to="delivery.DeliveryBoyDocumentPhotos",
            ),
        ),
    ]
