# Generated by Django 3.0.8 on 2022-02-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_auto_20220130_0908"),
        ("delivery", "0015_auto_20220205_2148"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryboy",
            name="store",
        ),
        migrations.AddField(
            model_name="deliveryboy",
            name="store",
            field=models.ManyToManyField(
                blank=True, related_name="store_delivery_boy", to="store.Store"
            ),
        ),
    ]
