# Generated by Django 3.0.8 on 2022-02-12 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("delivery", "0016_auto_20220211_0420"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deliveryboy",
            unique_together={("user",)},
        ),
    ]
