# Generated by Django 3.1.14 on 2022-02-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0017_auto_20220212_1341"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryboy",
            name="current_location",
        ),
    ]
