# Generated by Django 3.1.14 on 2022-03-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0020_auto_20220306_1725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryboy",
            name="status",
            field=models.CharField(
                choices=[
                    ("offline", "Offline"),
                    ("online", "Online"),
                    ("ready_for_order_picked_up", "Ready for order picked up"),
                    ("order_picked_up", "Order picked up"),
                    ("delivery_on_the_way", "Delivery on the way"),
                ],
                default="offline",
                max_length=255,
            ),
        ),
    ]
