# Generated by Django 3.1.14 on 2022-03-07 18:00

import base.file_dir
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0021_auto_20220306_1808"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryboydocument",
            name="photos",
        ),
        migrations.AddField(
            model_name="deliveryboydocument",
            name="back",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.file_dir.delivery_boy_document_back,
            ),
        ),
        migrations.AddField(
            model_name="deliveryboydocument",
            name="front",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.file_dir.delivery_boy_document_front,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryboyvehiclephotos",
            name="original",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.file_dir.delivery_boy_vehicle_original_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryboyvehiclephotos",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.file_dir.delivery_boy_vehicle_thumbnail_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryboyvehiclephotos",
            name="webp_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.file_dir.delivery_boy_vehicle_webp_upload_path,
            ),
        ),
        migrations.DeleteModel(
            name="DeliveryBoyDocumentPhotos",
        ),
    ]
