# Generated by Django 3.1.14 on 2022-03-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0022_auto_20220307_1800"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryboy",
            name="bank_account_ifsc_code",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="deliveryboy",
            name="bank_account_name",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="deliveryboy",
            name="bank_account_number",
            field=models.CharField(default="", max_length=50),
        ),
    ]
