# Generated by Django 3.1.14 on 2022-03-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0023_auto_20220307_1810"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryboy",
            name="bank_branch_address",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="deliveryboy",
            name="bank_branch_name",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="deliveryboy",
            name="bank_name",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="deliveryboypayoutinformation",
            name="bank_name",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
