# Generated by Django 3.1.14 on 2022-03-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_auto_20220307_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryboy',
            old_name='status',
            new_name='current_status',
        ),
    ]
