# Generated by Django 3.1.14 on 2022-04-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0027_remove_deliveryboy_is_approve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryboydocument',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='deliveryboypayoutinformation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='deliveryboyreview',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='deliveryboyvehicleinformation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='deliveryboyvehiclephotos',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='deliverycharges',
            options={'ordering': ['-id']},
        ),
    ]
