# Generated by Django 3.0.8 on 2022-01-11 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("sequence", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "slug",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("description", models.TextField(default="")),
                (
                    "product_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.Category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
