# Generated by Django 3.0.8 on 2022-01-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="category",
            name="webp_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
