# Generated by Django 3.0.8 on 2022-01-14 10:44

from django.db import migrations, models

import base.file_dir


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_auto_20220114_1036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=base.file_dir.category_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.file_dir.category_thumbnail_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="webp_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.file_dir.category_webp_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="productphoto",
            name="original",
            field=models.ImageField(
                blank=True, null=True, upload_to=base.file_dir.product_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="productphoto",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.file_dir.category_thumbnail_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="productphoto",
            name="webp_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.file_dir.product_webp_upload_path,
            ),
        ),
    ]
