# Generated by Django 3.0.8 on 2022-01-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_auto_20220114_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="background_color",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
