# Generated by Django 3.0.8 on 2022-01-15 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_category_background_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurement",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="measurement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.Measurement",
            ),
        ),
    ]
