# Generated by Django 3.0.8 on 2022-01-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_auto_20220115_1233"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_main",
            field=models.BooleanField(default=True),
        ),
    ]
