# Generated by Django 3.0.8 on 2022-01-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_variation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="product_master",
        ),
    ]
