# Generated by Django 3.0.8 on 2022-01-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_remove_variation_product_master"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstockmaster",
            name="variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.Variation",
            ),
        ),
    ]
