# Generated by Django 3.0.8 on 2022-01-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_productstockmaster_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstockmaster",
            name="variation_quantity",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
