# Generated by Django 3.0.8 on 2022-01-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_productstockmaster_variation_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productstockmaster",
            name="variation_quantity",
        ),
    ]
