# Generated by Django 3.0.8 on 2022-01-17 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_variation_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variation",
                to="catalog.Product",
            ),
        ),
    ]
