# Generated by Django 3.0.8 on 2022-01-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_auto_20220117_1648"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productstockmaster",
            name="exclusive_rate",
        ),
        migrations.RemoveField(
            model_name="productstockmaster",
            name="max_order_quantity",
        ),
        migrations.RemoveField(
            model_name="productstockmaster",
            name="member_rate",
        ),
        migrations.RemoveField(
            model_name="productstockmaster",
            name="mrp",
        ),
        migrations.RemoveField(
            model_name="productstockmaster",
            name="open_stock",
        ),
        migrations.RemoveField(
            model_name="productstockmaster",
            name="our_rate",
        ),
        migrations.RemoveField(
            model_name="productstockmaster",
            name="purchase_rate",
        ),
        migrations.AddField(
            model_name="productstockmaster",
            name="type",
            field=models.CharField(
                choices=[("single", "Single"), ("variation", "Variation")],
                default="single",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="exclusive_rate",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="variation",
            name="max_order_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="variation",
            name="member_rate",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="variation",
            name="mrp",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="variation",
            name="open_stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="variation",
            name="our_rate",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="variation",
            name="purchase_rate",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
