# Generated by Django 3.0.8 on 2022-01-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_auto_20220117_1756"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tax",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    ("0", "Not attempt"),
                    ("5", "GST 5%"),
                    ("12", "GST 12%"),
                    ("14", "GST 14%"),
                    ("18", "GST 18%"),
                    ("28", "GST 28%"),
                ],
                default="0",
                null=True,
            ),
        ),
    ]
