# Generated by Django 3.0.8 on 2022-01-22 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0026_product_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productphoto",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_photos",
                to="catalog.Product",
            ),
        ),
    ]
