# Generated by Django 3.0.8 on 2022-01-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_auto_20220122_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tax",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Not attempt"),
                    ("5", "GST 5%"),
                    ("12", "GST 12%"),
                    ("14", "GST 14%"),
                    ("18", "GST 18%"),
                    ("28", "GST 28%"),
                ],
                default="0",
                max_length=5,
                null=True,
            ),
        ),
    ]
