# Generated by Django 3.0.8 on 2022-01-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_auto_20220123_0850"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="sub_category",
            new_name="parent_category",
        ),
    ]
