# Generated by Django 3.0.8 on 2022-01-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_auto_20220123_0908"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productstockmaster",
            name="discount",
        ),
        migrations.AddField(
            model_name="variation",
            name="discount",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
