# Generated by Django 3.0.8 on 2022-01-27 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import base.file_dir


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_auto_20220126_1254"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstockmaster",
            name="position",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="VariationPhoto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "original",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=base.file_dir.product_upload_path,
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=base.file_dir.product_webp_upload_path,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=base.file_dir.category_thumbnail_upload_path,
                    ),
                ),
                ("alt_text", models.TextField(default="")),
                ("is_default", models.BooleanField(default=False)),
                (
                    "variation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variation_photos",
                        to="catalog.Variation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
