# Generated by Django 3.0.8 on 2022-01-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0033_auto_20220127_1705"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variationphoto",
            name="variation",
        ),
    ]
