# Generated by Django 3.0.8 on 2022-01-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0034_remove_variationphoto_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="photos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variation_photos",
                to="catalog.VariationPhoto",
            ),
        ),
    ]
