# Generated by Django 3.0.8 on 2022-01-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0035_variation_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="photos",
        ),
        migrations.AddField(
            model_name="variation",
            name="photos",
            field=models.ManyToManyField(
                related_name="variation_photos", to="catalog.VariationPhoto"
            ),
        ),
    ]
