# Generated by Django 3.0.8 on 2022-01-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0036_auto_20220127_1751"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="variation_photos", to="catalog.VariationPhoto"
            ),
        ),
    ]
