# Generated by Django 3.0.8 on 2022-01-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0037_auto_20220127_1752"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productphoto",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="product_photos", to="catalog.ProductPhoto"
            ),
        ),
    ]
