# Generated by Django 3.0.8 on 2022-01-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0038_auto_20220127_1757"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productstockmaster",
            name="min_stock",
        ),
        migrations.AddField(
            model_name="variation",
            name="min_stock",
            field=models.IntegerField(default=0),
        ),
    ]
