# Generated by Django 3.0.8 on 2022-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0039_auto_20220129_2035"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="sequence",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
