# Generated by Django 3.0.8 on 2022-02-05 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0040_auto_20220130_0903"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="discount",
        ),
    ]
