# Generated by Django 3.0.8 on 2022-02-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0041_remove_variation_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="value",
            field=models.IntegerField(default=0),
        ),
    ]
