# Generated by Django 3.0.8 on 2022-02-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0042_auto_20220205_0841"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productstockmaster",
            name="is_free_delivery",
        ),
    ]
