# Generated by Django 3.0.8 on 2022-02-05 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0043_remove_productstockmaster_is_free_delivery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="product_count",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category",
                to="catalog.Category",
            ),
        ),
    ]
