# Generated by Django 3.0.8 on 2022-02-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_auto_20220130_0908"),
        ("catalog", "0046_auto_20220210_1839"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productstockmaster",
            name="store",
        ),
        migrations.AddField(
            model_name="productstockmaster",
            name="store",
            field=models.ManyToManyField(
                blank=True, related_name="store_product_stock_master", to="store.Store"
            ),
        ),
    ]
