# Generated by Django 3.0.8 on 2022-02-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0047_auto_20220211_0422"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="hsn_code",
        ),
        migrations.AddField(
            model_name="variation",
            name="hsn_code",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
