# Generated by Django 3.0.8 on 2022-02-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0048_auto_20220211_1828"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="long_description",
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
