# Generated by Django 3.0.8 on 2022-02-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0049_auto_20220215_1906"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="open_stock",
        ),
        migrations.AlterField(
            model_name="variation",
            name="min_stock",
            field=models.IntegerField(default=0, verbose_name="Alert quantity"),
        ),
    ]
