# Generated by Django 3.0.8 on 2022-02-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0050_auto_20220216_1841"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
