# Generated by Django 3.0.8 on 2022-02-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0051_auto_20220220_1319"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="unit",
        ),
        migrations.AddField(
            model_name="variation",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variantion_unit",
                to="catalog.Unit",
            ),
        ),
    ]
