# Generated by Django 3.1.14 on 2022-03-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0054_auto_20220220_1531"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="open_stock",
            field=models.IntegerField(default=0, verbose_name="Open stock"),
        ),
    ]
