# Generated by Django 3.0.8 on 2022-01-11 20:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "gst_number",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("address", models.TextField(blank=True, default="", null=True)),
                (
                    "geo_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "store_number",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "store_name",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=64, null=True)),
                ("state", models.CharField(blank=True, max_length=25, null=True)),
                ("country", models.CharField(blank=True, max_length=25, null=True)),
                ("pin_code", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "allow_geo_location_path",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_open", models.BooleanField(default=False)),
                ("is_warehouse_exists", models.BooleanField(default=False)),
                (
                    "owner_signature",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("time_start", models.TimeField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                ("delivery_time", models.TimeField(blank=True, null=True)),
                (
                    "slug",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "store_name")},
            },
        ),
    ]
