# Generated by Django 3.0.8 on 2022-01-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="owner_signature",
            field=models.ImageField(
                blank=True,
                null=True,
            ),
        ),
    ]
