# Generated by Django 3.0.8 on 2022-01-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_auto_20220114_1116"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_address_set_manually",
            field=models.BooleanField(default=False),
        ),
    ]
