# Generated by Django 3.0.8 on 2022-01-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_store_is_address_set_manually"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="store",
            unique_together={("store_number", "store_name")},
        ),
        migrations.RemoveField(
            model_name="store",
            name="country",
        ),
        migrations.RemoveField(
            model_name="store",
            name="gst_number",
        ),
        migrations.RemoveField(
            model_name="store",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="store",
            name="owner_signature",
        ),
    ]
