# Generated by Django 3.0.8 on 2022-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_auto_20220116_1913"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="store_number",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="store",
            unique_together={("store_name",)},
        ),
    ]
