# Generated by Django 3.0.8 on 2022-02-14 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_stocktransfer"),
        ("store", "0006_auto_20220213_0523"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="is_warehouse_exists",
        ),
        migrations.AddField(
            model_name="store",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.Warehouse",
            ),
        ),
    ]
