# Generated by Django 3.0.8 on 2022-02-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_auto_20220214_1832"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="delivery_time",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
