# Generated by Django 3.0.8 on 2022-02-20 18:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_auto_20220217_1643"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="allow_geo_location_path",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
