# Generated by Django 3.0.8 on 2022-01-09 16:11

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("forgot_password", "Forgot Password"),
                            ("reset_password", "Reset password"),
                            ("confirmation", "Confirmation Email"),
                            ("change_password", "Change password"),
                            ("account_deactivate", "Account Deactivate"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(default="", max_length=1024)),
                ("html_content", ckeditor.fields.RichTextField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
