# Generated by Django 3.0.8 on 2022-02-05 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("customer",)},
        ),
    ]
