# Generated by Django 3.0.8 on 2022-02-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_auto_20220205_0956"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="type",
            field=models.CharField(
                choices=[
                    ("one_month", "One month"),
                    ("half_year", "Half year"),
                    ("one_year", "One year"),
                    ("not_attempt", "Not attempt"),
                ],
                default="one_month",
                max_length=255,
            ),
        ),
    ]
