# Generated by Django 3.1.14 on 2022-02-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0005_membershipplain_benefits"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_membership_plan",
                to="membership.membershipplain",
            ),
        ),
    ]
