# Generated by Django 3.1.14 on 2022-02-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0006_membership_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipbenefits",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
