# Generated by Django 3.1.14 on 2022-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0007_membershipbenefits_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipplain",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
