# Generated by Django 3.1.14 on 2022-02-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_auto_20220227_1803"),
        ("membership", "0009_auto_20220227_0741"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_transaction",
                to="wallet.transaction",
            ),
        ),
    ]
