# Generated by Django 3.1.14 on 2022-02-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0010_membership_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="payment_token",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
