# Generated by Django 3.1.14 on 2022-02-27 19:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0011_membership_payment_token"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("customer",)},
        ),
    ]
