# Generated by Django 3.1.14 on 2022-04-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_auto_20220227_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipbenefits',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='membershipplain',
            options={'ordering': ['-id']},
        ),
    ]
