# Generated by Django 3.0.8 on 2022-01-26 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0004_auto_20220116_1913"),
        ("catalog", "0031_auto_20220126_1254"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "reference_number",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "tax",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Not attempt"),
                            ("5", "GST 5%"),
                            ("12", "GST 12%"),
                            ("14", "GST 14%"),
                            ("18", "GST 18%"),
                            ("28", "GST 28%"),
                        ],
                        default="0",
                        max_length=5,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(default="")),
                ("total_amount", models.FloatField(blank=True, default=0.0, null=True)),
                ("discount", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.Store",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_supplier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                ("quantity", models.IntegerField(default=0)),
                ("price", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_product",
                        to="catalog.Product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_purchase",
                        to="warehouse.Purchase",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.Unit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
