# Generated by Django 3.0.8 on 2022-02-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_stocktransfer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="price",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="product",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="unit",
        ),
        migrations.AddField(
            model_name="warehouse",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="city",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="country",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="pin_code",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="state",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
