# Generated by Django 3.0.8 on 2022-02-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0006_auto_20220217_1857"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasemultiitem",
            name="barcode",
        ),
    ]
