# Generated by Django 3.1.14 on 2022-03-08 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_auto_20220220_1814"),
        ("warehouse", "0007_remove_purchasemultiitem_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransfer",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="To Store",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="From warehouse",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.warehouse",
            ),
        ),
    ]
