# Generated by Django 3.1.14 on 2022-03-09 18:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0009_auto_20220308_1901"),
    ]

    operations = [
        migrations.AddField(
            model_name="storestockmanagement",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="storestockmanagement",
            name="transfer_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.stocktransfer",
            ),
        ),
        migrations.AddField(
            model_name="warehousestockmanagement",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="warehousestockmanagement",
            name="purchase_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.purchase",
            ),
        ),
    ]
