# Generated by Django 3.1.14 on 2022-04-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20220309_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='purchasemultiitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='stocktransfermultiitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='storestockmanagement',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='warehousestockmanagement',
            options={'ordering': ['-id']},
        ),
    ]
