# Generated by Django 5.1.3 on 2024-12-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0011_auto_20220403_1914"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase",
            options={},
        ),
        migrations.AlterModelOptions(
            name="purchasemultiitem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="stocktransfer",
            options={},
        ),
        migrations.AlterModelOptions(
            name="stocktransfermultiitem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="storestockmanagement",
            options={},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={},
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={},
        ),
        migrations.AlterModelOptions(
            name="warehousestockmanagement",
            options={},
        ),
        migrations.AlterField(
            model_name="purchase",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="purchasemultiitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfermultiitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="storestockmanagement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="warehousestockmanagement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
