# Generated by Django 3.0.8 on 2022-02-12 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery", "0017_auto_20220212_1341"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerWallet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "balance_amount",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("customer",)},
            },
        ),
        migrations.CreateModel(
            name="DeliveryBoyWallet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "balance_amount",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "delivery_boy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_boy_wallet",
                        to="delivery.DeliveryBoy",
                    ),
                ),
            ],
            options={
                "unique_together": {("delivery_boy",)},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, default="", null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("add_money_in_wallet", "Add money in wallet"),
                            ("cashback", "Cashback"),
                            ("not_attempt", "Not attempt"),
                        ],
                        default="not_attempt",
                        max_length=255,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("credit", "Credit (+)"),
                            ("debit", "Debit (-)"),
                            ("not_attempt", "Not attempt"),
                        ],
                        default="not_attempt",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wating", "Wating"),
                            ("successful", "Successful"),
                            ("failed", "Failed"),
                            ("not_attempt", "Not attempt"),
                        ],
                        default="not_attempt",
                        max_length=255,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("qr_code", "QR Code"),
                            ("wallet", "Wallet"),
                            ("online", "Online"),
                            ("cash", "Cash"),
                            ("not_attempt", "Not attempt"),
                        ],
                        default="not_attempt",
                        max_length=255,
                    ),
                ),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("amount", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "customer_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_wallet_transaction",
                        to="wallet.CustomerWallet",
                    ),
                ),
                (
                    "delivery_boy_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_boy_wallet_transaction",
                        to="wallet.DeliveryBoyWallet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
