# Generated by Django 3.0.8 on 2022-02-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_transaction_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_payload",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
