# Generated by Django 3.0.8 on 2022-02-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_transaction_payment_payload"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_response",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
