# Generated by Django 3.1.14 on 2022-02-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_transaction_payment_response"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="type",
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("payment", "Payment"),
                    ("refund", "Refund"),
                    ("add_money_in_wallet", "Add money in wallet"),
                    ("add_membership", "Add membership"),
                    ("cashback", "Cashback"),
                    ("not_attempt", "Not attempt"),
                ],
                default="not_attempt",
                max_length=255,
            ),
        ),
    ]
