# Generated by Django 3.1.14 on 2022-03-06 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0034_auto_20220306_1823"),
        ("wallet", "0005_auto_20220227_1803"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseOnDeliveryCollectionHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, default="", null=True)),
                (
                    "reference",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("amount", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "delivery_boy_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transaction",
                        to="wallet.deliveryboywallet",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_boy_order",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
