# Generated by Django 3.0.8 on 2022-01-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="refund_method",
        ),
    ]
