# Generated by Django 3.0.8 on 2022-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_auto_20220129_2248"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sequence",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
