# Generated by Django 3.0.8 on 2022-02-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_auto_20220130_1821"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="no_contact_delivery",
            field=models.BooleanField(default=False),
        ),
    ]
