# Generated by Django 3.0.8 on 2022-02-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_delivery_boy_tip"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_membership_exist",
            field=models.BooleanField(default=False),
        ),
    ]
