# Generated by Django 3.0.8 on 2022-02-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_is_membership_exist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="is_membership_exist",
            new_name="new_membership_adding",
        ),
    ]
