# Generated by Django 3.0.8 on 2022-02-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_auto_20220205_0648"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="delivery_boy_tip",
            new_name="final_delivery_boy_tip",
        ),
    ]
