# Generated by Django 3.0.8 on 2022-02-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_auto_20220205_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("wating", "Wating"),
                    ("successful", "Successful"),
                    ("failed", "Failed"),
                    ("not_attempt", "Not attempt"),
                ],
                default="wating",
                max_length=255,
            ),
        ),
    ]
