# Generated by Django 3.0.8 on 2022-02-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("wating", "Wating"),
                    ("successful", "Successful"),
                    ("failed", "Failed"),
                ],
                default="wating",
                max_length=255,
            ),
        ),
    ]
