# Generated by Django 3.0.8 on 2022-02-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_auto_20220205_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("one_month", "One month"),
                    ("half_year", "Half year"),
                    ("one_year", "One year"),
                    ("not_attempt", "Not attempt"),
                ],
                default="not_attempt",
                max_length=255,
            ),
        ),
    ]
