# Generated by Django 3.0.8 on 2022-02-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0023_finaldeliveredorder_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="package_weight",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
