# Generated by Django 3.0.8 on 2022-02-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_order_package_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_token",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_link",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
