# Generated by Django 3.0.8 on 2022-02-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_transaction_payment_response"),
        ("orders", "0025_auto_20220215_2203"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_transaction",
                to="wallet.Transaction",
            ),
        ),
    ]
