# Generated by Django 3.0.8 on 2022-02-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_auto_20220221_1811"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="dropzone",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
