# Generated by Django 3.1.14 on 2022-02-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0029_auto_20220225_1743"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_link",
        ),
    ]
