# Generated by Django 3.1.14 on 2022-02-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0030_remove_order_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_token",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
