# Generated by Django 3.1.14 on 2022-02-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0031_auto_20220226_1712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("one_month", "One month"),
                    ("three_month", "Three month"),
                    ("half_year", "Half year"),
                    ("one_year", "One year"),
                    ("not_attempt", "Not attempt"),
                ],
                default="not_attempt",
                max_length=255,
            ),
        ),
    ]
