# Generated by Django 3.1.14 on 2022-03-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("package", "0001_initial"),
        ("orders", "0032_auto_20220226_1924"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="package_boy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_pack",
                to="package.packageboy",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="package_time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="package_time_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
