# Generated by Django 3.1.14 on 2022-03-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0033_auto_20220303_1903"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="collect_amount",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="wallet_amount_used",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
