# Generated by Django 3.1.14 on 2022-04-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20220306_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finaldeliveredorder',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
    ]
