# Generated by Django 3.0.8 on 2022-01-27 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0038_auto_20220127_1757"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                ("rate", models.FloatField(blank=True, default=0.0, null=True)),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                ("is_lock", models.BooleanField(default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_stock_master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_stock_master",
                        to="catalog.ProductStockMaster",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
