# Generated by Django 3.0.8 on 2022-01-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_checkout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkout",
            old_name="total",
            new_name="final_total",
        ),
    ]
