# Generated by Django 3.0.8 on 2022-01-29 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0039_auto_20220129_2035"),
        ("cart", "0004_auto_20220127_1858"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product_stock_master",
        ),
        migrations.AddField(
            model_name="cart",
            name="product_variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_product_variation",
                to="catalog.Variation",
            ),
        ),
    ]
