# Generated by Django 3.0.8 on 2022-01-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_auto_20220129_2112"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="is_lock_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
