# Generated by Django 3.0.8 on 2022-01-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_cart_is_lock_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
