# Generated by Django 3.0.8 on 2022-01-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_auto_20220129_2142"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
