# Generated by Django 3.0.8 on 2022-01-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_auto_20220129_2143"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="final_tax",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
