# Generated by Django 3.0.8 on 2022-01-30 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_auto_20220130_0908"),
        ("cart", "0009_checkout_final_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_cart",
                to="store.Store",
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_checkout",
                to="store.Store",
            ),
        ),
    ]
