# Generated by Django 3.0.8 on 2022-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_auto_20220130_1756"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="final_quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
