# Generated by Django 3.0.8 on 2022-02-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0012_remove_checkout_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="no_contact_delivery",
            field=models.BooleanField(default=False),
        ),
    ]
