# Generated by Django 3.0.8 on 2022-02-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0017_auto_20220205_1025"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="membership_saving",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="checkout",
            name="our_store_saving",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
