# Generated by Django 3.0.8 on 2022-02-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0019_checkout_membership_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="final_membership_fee",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
