# Generated by Django 3.0.8 on 2022-02-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0020_checkout_final_membership_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="is_lock",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="is_lock_at",
        ),
    ]
