# Generated by Django 3.0.8 on 2022-02-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0021_auto_20220205_2047"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "Cash on delivery"),
                    ("online", "Online"),
                ],
                default="online",
                max_length=255,
            ),
        ),
    ]
