# Generated by Django 3.0.8 on 2022-02-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_order_transaction"),
        ("cart", "0022_checkout_order_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkout_order",
                to="orders.Order",
            ),
        ),
    ]
