# Generated by Django 3.0.8 on 2022-02-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0008_auto_20220218_2238"),
        ("cart", "0023_checkout_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="discount_and_voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkout_discount_and_voucher",
                to="promotion.DiscountVoucher",
            ),
        ),
    ]
