# Generated by Django 3.1.14 on 2022-04-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_auto_20220226_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-id']},
        ),
    ]
