# Generated by Django 3.1.14 on 2022-02-27 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_deleted", models.BooleanField(default=False)),
                ("endpoint", models.TextField(default="")),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("http_code", models.PositiveSmallIntegerField(default=0)),
                ("http_method", models.CharField(max_length=10, null=True)),
                ("remote_address", models.CharField(max_length=20, null=True)),
                ("latency_time", models.IntegerField(default=0)),
                ("traceback", models.TextField(default="")),
                ("body_request", models.TextField(default="")),
                ("body_response", models.TextField(default="")),
                ("body_response_size", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
