# Generated by Django 3.1.14 on 2022-02-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="user_token",
            field=models.TextField(default=""),
        ),
    ]
